name: darvin_app
description: A Darvin-generated Flutter app
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.8.0
  provider: ^6.1.1
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  connectivity_plus: ^6.1.4
  path: ^1.9.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.7
  collection: ^1.18.0
  async: ^2.12.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  supabase_flutter: ^2.9.1
  go_router: ^14.1.4
  flutter_svg: ^2.2.0
  google_fonts: ^6.1.0
  flex_color_scheme: ^8.2.0
  loading_animation_widget: ^1.2.1
  animations: ^2.0.11
  flutter_spinkit: ^5.2.1
  flutter_animate: ^4.5.2
  shimmer_animation: ^2.2.2
  intl: ^0.20.2
  uuid: ^4.2.1
  vector_math: ^2.1.4
  get_it: ^7.6.7
  rename_app: ^1.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
dependency_overrides:
  shared_preferences_android: 2.3.3
  path_provider_android: 2.2.10
  connectivity_plus: 6.0.5
  app_links: 6.3.2
  url_launcher_android: 6.3.12
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
  remove_alpha_ios: true
  android_min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/app_icon.png
  ios_content_mode: scaleAspectFit
